name: Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        env:
          PROD: ${{ secrets.PROD }}
          PROD_DB: ${{ secrets.PROD_DB }}
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: PROD,PROD_DB,ENV
          script: |
            if [ -d "taskimatti_old" ]; then
              rm -rf taskimatti_old
            fi
            if [ -d "taskimatti" ]; then
              cd taskimatti
              cd directus
              sh backup.sh
              cd ..
              docker compose -f compose.yaml down
              cd ..
              mv taskimatti taskimatti_old
            fi
            git clone https://github.com/taskimatti/taskimatti.git
            cd taskimatti
            echo $ENV | tr ' ' '\n' > ./app/.env
            echo $PROD | tr ' ' '\n' > .env.prod
            echo $PROD_DB | tr ' ' '\n' > .env.prod.db
            docker compose -f compose.yaml up -d --build
            docker exec -u root Directus chown -R node:node /directus/extensions /directus/uploads
